
# YAML build Script for Notes

trigger:
  batch: true
  branches:
    include:
    - ci

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build jacocoTestReport'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/app/build/JaCoCoReports/*Debug*/**.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/app/src/main/java'
    reportDirectory: '$(System.DefaultWorkingDirectory)./app/build/JaCoCoReports/*Debug*/html/'

