
# YAML build Script for Notes

trigger:
  batch: true
  branches:
    include:
    - rework
    - ci

pool:
  vmImage: 'macos-latest'

jobs:
  - job: DEBUG
    steps:
      - template: androidBuildAndPublishTestTemplate.yml
        parameters:
          BUILD_TYPE: 'Debug'


