

# YAML build Script for Notes

variables:
  - group: ReleaseNameVariables

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'macos-latest'

jobs:
  - job: RELEASE
    steps:
      - template: androidBuildAndPublishTestTemplate.yml
        parameters:
          BUILD_TYPE: 'Release'


