# YAML build Script for Notes
variables:
  - group: ReleaseNameVariables

# trigger for all branches
trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
      - master

pool:
  vmImage: 'macos-latest'

jobs:
  - job: DEBUG_Build
    steps:
      - template: androidBuildAndPublishTestTemplate.yml
        parameters:
          BUILD_TYPE: 'Debug'

  - job: Compile_ReleaseNotes_Curr_Iter
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: '$(System.DefaultWorkingDirectory)/ci/generateReleaseNotes.ps1'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            ls
            cd ./ci
            ls
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/ci'
          Contents: '*.md'
          TargetFolder: '$(build.artifactstagingdirectory)/ReleaseNotes'
          CleanTargetFolder: true
          flattenFolders: true
      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/ReleaseNotes'
          ArtifactName: 'ReleaseNotes'
          publishLocation: 'Container'

