# YAML build Script for Notes
variables:
  - group: ReleaseNameVariables

# trigger for all branches
trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: DEBUG_Build
    steps:
      #- template: androidBuildAndPublishTestTemplate.yml
      #  parameters:
      #    BUILD_TYPE: 'Debug'
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: '$(System.DefaultWorkingDirectory)/ci/generateReleaseNotes.ps1'

