

# YAML build Script for Notes
# builds a release build and signs the resulting apk

variables:
  - group: ReleaseNameVariables
  - group: Signing Keys

# is only triggered on master branch
trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'macos-latest'

jobs:
  - job: RELEASE
    steps:
      - template: androidBuildAndPublishTestTemplate.yml
        parameters:
          BUILD_TYPE: 'Release'

      - task: AndroidSigning@3
        condition: succeeded()
        displayName: 'Signing and aligning APK file(s) $(System.DefaultWorkingDirectory)/unsignedBuild/dropRelease/app-release-unsigned.apk'
        inputs:
          apkFiles: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/Release/app-release-unsigned.apk'
          apksignerKeystoreFile: azurekeystore
          apksignerKeystorePassword: '$(KeyStorePass)'
          apksignerKeystoreAlias: 'azure pipeline'
          apksignerKeyPassword: '$(KeyPass)'
          apksignerArguments: '--verbose'
      
      # copy & rename signed package
      - task: Bash@3
        condition: succeeded()
        inputs:
          targetType: 'inline'
          script: 
            mkdir '$(System.DefaultWorkingDirectory)/signed'
            cp '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/Release/app-release-unsigned.apk' '$(System.DefaultWorkingDirectory)/signed/notes-release-signed.apk'

      # publish signed apk
      - task: PublishBuildArtifacts@1
        condition: succeeded()
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/signed'
          ArtifactName: 'signed_apk'
          publishLocation: 'Container'



