

# YAML build Script for Notes
# builds a release build and signs the resulting apk

variables:
  - group: ReleaseNameVariables
  - group: Signing Keys

# is only triggered on master branch
trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'macos-latest'

jobs:
  - job: RELEASE
    steps:
      - template: androidBuildAndPublishTestTemplate.yml
        parameters:
          BUILD_TYPE: 'Release'

      - task: AndroidSigning@3
        displayName: 'Signing and aligning APK file(s) $(System.DefaultWorkingDirectory)/unsignedBuild/dropRelease/app-release-unsigned.apk'
        inputs:
          apkFiles: './app/build/outputs/apk/Release/app-release-unsigned.apk'
          apksignerKeystoreFile: azurekeystore
          apksignerKeystorePassword: '$(KeyStorePass)'
          apksignerKeystoreAlias: 'azure pipeline'
          apksignerKeyPassword: '$(KeyPass)'
          apksignerArguments: '--verbose'
      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/unsignedBuild/dropRelease/app-release-unsigned.apk'
          ArtifactName: 'signed_apk'
          publishLocation: 'Container'



